export const users = [
    {
      id: 1,
      name: "Leanne Graham",
      username: "Bret",
      email: "Sincere@april.biz",
      address: {
        street: "Kulas Light",
        suite: "Apt. 556",
        city: "Gwenborough",
        zipcode: "92998-3874",
        geo: {
          lat: "-37.3159",
          lng: "81.1496",
        },
      },
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      company: {
        name: "Romaguera-Crona",
        catchPhrase: "Multi-layered client-server neural-net",
        bs: "harness real-time e-markets",
      },
    },
    {
      id: 2,
      name: "Ervin Howell",
      username: "Antonette",
      email: "Shanna@melissa.tv",
      address: {
        street: "Victor Plains",
        suite: "Suite 879",
        city: "Wisokyburgh",
        zipcode: "90566-7771",
        geo: {
          lat: "-43.9509",
          lng: "-34.4618",
        },
      },
      phone: "010-692-6593 x09125",
      website: "anastasia.net",
      company: {
        name: "Deckow-Crist",
        catchPhrase: "Proactive didactic contingency",
        bs: "synergize scalable supply-chains",
      },
    },
    {
      id: 3,
      name: "Clementine Bauch",
      username: "Samantha",
      email: "Nathan@yesenia.net",
      address: {
        street: "Douglas Extension",
        suite: "Suite 847",
        city: "McKenziehaven",
        zipcode: "59590-4157",
        geo: {
          lat: "-68.6102",
          lng: "-47.0653",
        },
      },
      phone: "1-463-123-4447",
      website: "ramiro.info",
      company: {
        name: "Romaguera-Jacobson",
        catchPhrase: "Face to face bifurcated interface",
        bs: "e-enable strategic applications",
      },
    },
    {
      id: 4,
      name: "Patricia Lebsack",
      username: "Karianne",
      email: "Julianne.OConner@kory.org",
      address: {
        street: "Hoeger Mall",
        suite: "Apt. 692",
        city: "South Elvis",
        zipcode: "53919-4257",
        geo: {
          lat: "29.4572",
          lng: "-164.2990",
        },
      },
      phone: "493-170-9623 x156",
      website: "kale.biz",
      company: {
        name: "Robel-Corkery",
        catchPhrase: "Multi-tiered zero tolerance productivity",
        bs: "transition cutting-edge web services",
      },
    },
    {
      id: 5,
      name: "Chelsey Dietrich",
      username: "Kamren",
      email: "Lucio_Hettinger@annie.ca",
      address: {
        street: "Skiles Walks",
        suite: "Suite 351",
        city: "Roscoeview",
        zipcode: "33263",
        geo: {
          lat: "-31.8129",
          lng: "62.5342",
        },
      },
      phone: "(254)954-1289",
      website: "demarco.info",
      company: {
        name: "Keebler LLC",
        catchPhrase: "User-centric fault-tolerant solution",
        bs: "revolutionize end-to-end systems",
      },
    },
    {
      id: 6,
      name: "Mrs. Dennis Schulist",
      username: "Leopoldo_Corkery",
      email: "Karley_Dach@jasper.info",
      address: {
        street: "Norberto Crossing",
        suite: "Apt. 950",
        city: "South Christy",
        zipcode: "23505-1337",
        geo: {
          lat: "-71.4197",
          lng: "71.7478",
        },
      },
      phone: "1-477-935-8478 x6430",
      website: "ola.org",
      company: {
        name: "Considine-Lockman",
        catchPhrase: "Synchronised bottom-line interface",
        bs: "e-enable innovative applications",
      },
    },
    {
      id: 7,
      name: "Kurtis Weissnat",
      username: "Elwyn.Skiles",
      email: "Telly.Hoeger@billy.biz",
      address: {
        street: "Rex Trail",
        suite: "Suite 280",
        city: "Howemouth",
        zipcode: "58804-1099",
        geo: {
          lat: "24.8918",
          lng: "21.8984",
        },
      },
      phone: "210.067.6132",
      website: "elvis.io",
      company: {
        name: "Johns Group",
        catchPhrase: "Configurable multimedia task-force",
        bs: "generate enterprise e-tailers",
      },
    },
    {
      id: 8,
      name: "Nicholas Runolfsdottir V",
      username: "Maxime_Nienow",
      email: "Sherwood@rosamond.me",
      address: {
        street: "Ellsworth Summit",
        suite: "Suite 729",
        city: "Aliyaview",
        zipcode: "45169",
        geo: {
          lat: "-14.3990",
          lng: "-120.7677",
        },
      },
      phone: "586.493.6943 x140",
      website: "jacynthe.com",
      company: {
        name: "Abernathy Group",
        catchPhrase: "Implemented secondary concept",
        bs: "e-enable extensible e-tailers",
      },
    },
    {
      id: 9,
      name: "Glenna Reichert",
      username: "Delphine",
      email: "Changdu@gmail.com",
      address: {
        street: "Dayna Park",
        suite: "Suite 449",
        city: "Bartholomebury",
        zipcode: "76495-3109",
        geo: {
          lat: "24.6463",
          lng: "-168.8889",
        },
      },
      phone: "(775)976-6794 x41206",
      website: "conrad.com",
      company: {
        name: "Yost and Sons",
        catchPhrase: "Switchable contextually-based project",
        bs: "aggregate real-time technologies",
      },
    },
    {
      id: 10,
      name: "Clementina DuBuque",
      username: "Moriah.Stanton",
      email: "Rey.Padberg@karina.biz",
      address: {
        street: "Kattie Turnpike",
        suite: "Suite 198",
        city: "Lebsackbury",
        zipcode: "31428-2261",
        geo: {
          lat: "-38.2386",
          lng: "57.2232",
        },
      },
      phone: "024-648-3804",
      website: "ambrose.net",
      company: {
        name: "Hoeger LLC",
        catchPhrase: "Centralized empowering task-force",
        bs: "target end-to-end models",
      },
    },
    {
      id: 11,
      name: "Oliver Twist",
      username: "Olivert",
      email: "oliver@twist.com",
      address: {
        street: "Broadway",
        suite: "Apt 12",
        city: "London",
        zipcode: "W1D 3",
        geo: {
          lat: "51.5142",
          lng: "-0.1295",
        },
      },
      phone: "020-123-4567",
      website: "olivertwist.com",
      company: {
        name: "Twist Co.",
        catchPhrase: "Bringing new stories to life",
        bs: "Publishing",
      },
    },
    {
      id: 12,
      name: "Sherlock Holmes",
      username: "sholmes",
      email: "sherlock@holmes.com",
      address: {
        street: "Baker Street",
        suite: "",
        city: "London",
        zipcode: "NW1 6XE",
        geo: {
          lat: "51.5238",
          lng: "-0.1580",
        },
      },
      phone: "020-456-7890",
      website: "sherlockholmes.com",
      company: {
        name: "Holmes and Watson",
        catchPhrase: "Solving the unsolvable",
        bs: "Private investigation",
      },
    },
    {
      id: 13,
      name: "Atticus Finch",
      username: "afinch",
      email: "atticus@finch.com",
      address: {
        street: "Oak Lane",
        suite: "",
        city: "Maycomb",
        zipcode: "36426",
        geo: {
          lat: "31.7100",
          lng: "-87.4668",
        },
      },
      phone: "555-555-5555",
      website: "atticusfinch.com",
      company: {
        name: "Law Firm of Atticus Finch",
        catchPhrase: "Defending the innocent",
        bs: "Legal Services",
      },
    },
    {
      id: 14,
      name: "Holden Caulfield",
      username: "hcaulfield",
      email: "holden@caulfield.com",
      address: {
        street: "Park Avenue",
        suite: "",
        city: "New York",
        zipcode: "10065",
        geo: {
          lat: "40.7683",
          lng: "-73.9647",
        },
      },
      phone: "212-555-1212",
      website: "catcherintherye.com",
      company: {
        name: "J.D. Salinger Co.",
        catchPhrase: "Telling it like it is",
        bs: "Publishing",
      },
    },
    {
      id: 15,
      name: "Jane Eyre",
      username: "jeyre",
      email: "jane@eyre.com",
      address: {
        street: "Thornfield Hall",
        suite: "",
        city: "Millcote",
        zipcode: "X4Y 1ZP",
        geo: {
          lat: "52.6260",
          lng: "-1.4520",
        },
      },
      phone: "555-123-4567",
      website: "janeeyre.com",
      company: {
        name: "Gateshead Hall",
        catchPhrase: "Breaking free from oppression",
        bs: "Publishing",
      },
    },
    {
      id: 16,
      name: "Dorian Gray",
      username: "dgray",
      email: "dorian@gray.com",
      address: {
        street: "Grosvenor Square",
        suite: "",
        city: "London",
        zipcode: "W1K 2HP",
        geo: {
          lat: "51.5099",
          lng: "-0.1495",
        },
      },
      phone: "+44 20 1234 5678",
      website: "pictureofdoriangray.com",
      company: {
        name: "Wotton & Co.",
        catchPhrase: "Living for pleasure",
        bs: "Publishing",
      },
    },
    {
      id: 17,
      name: "Holly Golightly",
      username: "hgolightly",
      email: "holly@golightly.com",
      address: {
        street: "Tiffany & Co.",
        suite: "",
        city: "New York",
        zipcode: "10022",
        geo: {
          lat: "40.7588",
          lng: "-73.9787",
        },
      },
      phone: "212-555-6789",
      website: "breakfastattiffanys.com",
      company: {
        name: "Holly's Place",
        catchPhrase: "Living in style",
        bs: "Fashion",
      },
    },
    {
      id: 18,
      name: "Jay Gatsby",
      username: "jgatsby",
      email: "jay@gatsby.com",
      address: {
        street: "West Egg",
        suite: "",
        city: "Long Island",
        zipcode: "11953",
        geo: {
          lat: "40.8773",
          lng: "-72.4587",
        },
      },
      phone: "555-555-5555",
      website: "thegreatgatsby.com",
      company: {
        name: "Gatsby's",
        catchPhrase: "Living the American Dream",
        bs: "Entertainment",
      },
    },
    {
      id: 19,
      name: "Elizabeth Bennet",
      username: "ebennet",
      email: "elizabeth@bennet.com",
      address: {
        street: "Longbourn House",
        suite: "",
        city: "Hertfordshire",
        zipcode: "SG18 9RH",
        geo: {
          lat: "51.8793",
          lng: "-0.4207",
        },
      },
      phone: "555-555-5555",
      website: "prideandprejudice.com",
      company: {
        name: "Bennet & Co.",
        catchPhrase: "Breaking social conventions",
        bs: "Publishing",
      },
    },
    {
      id: 20,
      name: "Atticus O'Sullivan",
      username: "a.osullivan",
      email: "atticus@osullivan.com",
      address: {
        street: "Powell's Books",
        suite: "Suite 700",
        city: "Portland",
        zipcode: "97209",
        geo: {
          lat: "45.5230",
          lng: "-122.6814",
        },
      },
      phone: "555-555-5555",
      website: "irondruidchronicles.com",
      company: {
        name: "O'Sullivan & Co.",
        catchPhrase: "Keeping the world safe from supernatural threats",
        bs: "Security",
      },
    },
    {
      id: 21,
      name: "Rand al'Thor",
      username: "ralthor",
      email: "rand@althor.com",
      address: {
        street: "The White Tower",
        suite: "",
        city: "Tar Valon",
        zipcode: "01479",
        geo: {
          lat: "57.3623",
          lng: "-2.7990",
        },
      },
      phone: "555-555-5555",
      website: "wheeloftime.com",
      company: {
        name: "The Dragon Reborn",
        catchPhrase: "Saving the world from the Dark One",
        bs: "Security",
      },
    },
    {
      id: 22,
      name: "Kvothe",
      username: "kvothe",
      email: "kvothe@edema.com",
      address: {
        street: "University",
        suite: "",
        city: "Imre",
        zipcode: "35001",
        geo: {
          lat: "42.5406",
          lng: "-70.8803",
        },
      },
      phone: "555-555-5555",
      website: "kingkiller.com",
      company: {
        name: "Edema Ruh",
        catchPhrase: "Telling stories is a powerful magic",
        bs: "Entertainment",
      },
    },
    {
      id: 23,
      name: "Holly Golightly",
      username: "hgolightly",
      email: "holly@golightly.com",
      address: {
        street: "Tiffany & Co.",
        suite: "Fifth Avenue",
        city: "New York",
        zipcode: "10022",
        geo: {
          lat: "40.7585",
          lng: "-73.9787",
        },
      },
      phone: "555-555-5555",
      website: "breakfastattiffanys.com",
      company: {
        name: "Golightly Inc.",
        catchPhrase: "Living for the moment",
        bs: "Retail",
      },
    },
    {
      id: 24,
      name: "Sara Crewe",
      username: "screwe",
      email: "sara@crewe.com",
      address: {
        street: "Miss Minchin's Select Seminary for Young Ladies",
        suite: "",
        city: "London",
        zipcode: "W1U 7RS",
        geo: {
          lat: "51.5194",
          lng: "-0.1495",
        },
      },
      phone: "555-555-5555",
      website: "alittleprincess.com",
      company: {
        name: "Crewe & Co.",
        catchPhrase: "Fortune favors the brave",
        bs: "Education",
      },
    },
    {
      id: 25,
      name: "Howard Roark",
      username: "hroark",
      email: "howard@roark.com",
      address: {
        street: "The Enright House",
        suite: "",
        city: "New York",
        zipcode: "10021",
        geo: {
          lat: "40.7686",
          lng: "-73.9601",
        },
      },
      phone: "555-555-5555",
      website: "thefountainhead.com",
      company: {
        name: "Roark & Associates",
        catchPhrase: "Individualism above all",
        bs: "Architecture",
      },
    },
    {
      id: 26,
      name: "Elinor Dashwood",
      username: "edashwood",
      email: "elinor@dashwood.com",
      address: {
        street: "Norland Park",
        suite: "",
        city: "Sussex",
        zipcode: "RH17 7EY",
        geo: {
          lat: "51.0262",
          lng: "-0.3006",
        },
      },
      phone: "555-555-5555",
      website: "senseandsensibility.com",
      company: {
        name: "Dashwood & Co.",
        catchPhrase: "Sense and sensibility in all matters",
        bs: "Publishing",
      },
    },
    {
      id: 27,
      name: "Violet Crawley",
      username: "vcrawley",
      email: "violet@crawley.com",
      address: {
        street: "Downton Abbey",
        suite: "",
        city: "Yorkshire",
        zipcode: "YO62 5EB",
        geo: {
          lat: "54.2361",
          lng: "-1.2152",
        },
      },
      phone: "555-555-5555",
      website: "downtonabbey.com",
      company: {
        name: "Crawley & Sons",
        catchPhrase: "Tradition and progress",
        bs: "Noble family",
      },
    },
    {
      id: 28,
      name: "Elizabeth Swann",
      username: "eswann",
      email: "elizabeth@swann.com",
      address: {
        street: "Port Royal",
        suite: "",
        city: "Jamaica",
        zipcode: "none",
        geo: {
          lat: "17.9369",
          lng: "-76.8419",
        },
      },
      phone: "555-555-5555",
      website: "piratesofthecaribbean.com",
      company: {
        name: "Swann Shipping Company",
        catchPhrase: "Navigating the high seas",
        bs: "Shipping",
      },
    },
    {
      id: 29,
      name: "Willy Wonka",
      username: "wwonka",
      email: "willy@wonka.com",
      address: {
        street: "Wonka's Chocolate Factory",
        suite: "",
        city: "London",
        zipcode: "W1U 7RS",
        geo: {
          lat: "51.5194",
          lng: "-0.1495",
        },
      },
      phone: "555-555-5555",
      website: "charlieandthechocolatefactory.com",
      company: {
        name: "Wonka Industries",
        catchPhrase: "Pure imagination",
        bs: "Confectionery",
      },
    },
    {
      id: 30,
      name: "Scarlett O'Hara",
      username: "sohara",
      email: "scarlett@ohara.com",
      address: {
        street: "Tara Plantation",
        suite: "",
        city: "Jonesboro",
        zipcode: "30236",
        geo: {
          lat: "33.5236",
          lng: "-84.3539",
        },
      },
      phone: "555-555-5555",
      website: "gonewiththewind.com",
      company: {
        name: "O'Hara Plantation",
        catchPhrase: "As God is my witness, I'll never be hungry again",
        bs: "Plantation",
      },
    },
    {
      id: 31,
      name: "John Carter",
      username: "jcarter",
      email: "john@carter.com",
      address: {
        street: "Virginia",
        suite: "",
        city: "Richmond",
        zipcode: "23219",
        geo: {
          lat: "37.5407",
          lng: "-77.4360",
        },
      },
      phone: "555-555-5555",
      website: "princessofmars.com",
      company: {
        name: "Carter Mining Company",
        catchPhrase: "Taking on the Red Martians",
        bs: "Mining",
      },
    },
    {
      id: 32,
      name: "Hermione Granger",
      username: "hgranger",
      email: "hermione@hogwarts.com",
      address: {
        street: "Hogwarts School of Witchcraft and Wizardry",
        suite: "",
        city: "Hogsmeade",
        zipcode: "PO10 8QT",
        geo: {
          lat: "51.0133",
          lng: "-0.2234",
        },
      },
      phone: "555-555-5555",
      website: "harrypotter.com",
      company: {
        name: "Ministry of Magic",
        catchPhrase: "Working for a better wizarding world",
        bs: "Wizarding",
      },
    },
    {
      id: 33,
      name: "Frodo Baggins",
      username: "fbaggins",
      email: "frodo@baggins.com",
      address: {
        street: "Bag End",
        suite: "",
        city: "Hobbiton",
        zipcode: "106",
        geo: {
          lat: "-37.8725",
          lng: "175.6823",
        },
      },
      phone: "555-555-5555",
      website: "lordoftherings.com",
      company: {
        name: "The Shire",
        catchPhrase: "Home of the hobbits",
        bs: "Agriculture",
      },
    },
    {
      id: 34,
      name: "Jack Sparrow",
      username: "jsparrow",
      email: "jack@sparrow.com",
      address: {
        street: "The Black Pearl",
        suite: "",
        city: "Caribbean Sea",
        zipcode: "none",
        geo: {
          lat: "21.4691",
          lng: "-78.6569",
        },
      },
      phone: "555-555-5555",
      website: "piratesofthecaribbean.com",
      company: {
        name: "Sparrow Enterprises",
        catchPhrase: "Unleashing the power of the sea",
        bs: "Piracy",
      },
    },
    {
      id: 35,
      name: "Indiana Jones",
      username: "ijones",
      email: "indiana@jones.com",
      address: {
        street: "Marshall College",
        suite: "",
        city: "Bedford",
        zipcode: "47421",
        geo: {
          lat: "38.8652",
          lng: "-86.4699",
        },
      },
      phone: "555-555-5555",
      website: "indianajones.com",
      company: {
        name: "Jones Archaeological Institute",
        catchPhrase: "Uncovering the mysteries of the past",
        bs: "Archaeology",
      },
    },
    {
      id: 36,
      name: "Ellen Ripley",
      username: "eripley",
      email: "ellen@ripley.com",
      address: {
        street: "USCSS Nostromo",
        suite: "",
        city: "Deep space",
        zipcode: "",
        geo: {
          lat: "-51.6056",
          lng: "-58.8878",
        },
      },
      phone: "555-555-5555",
      website: "alien.com",
      company: {
        name: "Weyland-Yutani Corporation",
        catchPhrase: "Building better worlds",
        bs: "Space exploration",
      },
    },
    {
      id: 37,
      name: "Neo",
      username: "neo",
      email: "neo@zion.com",
      address: {
        street: "Nebuchadnezzar",
        suite: "",
        city: "Zion",
        zipcode: "",
        geo: {
          lat: "43.7167",
          lng: "7.2667",
        },
      },
      phone: "555-555-5555",
      website: "thematrix.com",
      company: {
        name: "Zion Corporation",
        catchPhrase: "Freeing minds since 1999",
        bs: "Cybersecurity",
      },
    },
    {
      id: 38,
      name: "Tony Stark",
      username: "tstark",
      email: "tony@starkindustries.com",
      address: {
        street: "10880 Malibu Point",
        suite: "",
        city: "Malibu",
        zipcode: "90265",
        geo: {
          lat: "34.0058",
          lng: "-118.8090",
        },
      },
      phone: "555-555-5555",
      website: "marvel.com",
      company: {
        name: "Stark Industries",
        catchPhrase: "Engineering tomorrow",
        bs: "Engineering",
      },
    },
    {
      id: 39,
      name: "Gandalf",
      username: "gandalf",
      email: "gandalf@middleearth.com",
      address: {
        street: "Bag End",
        suite: "",
        city: "Hobbiton",
        zipcode: "106",
        geo: {
          lat: "-37.8725",
          lng: "175.6823",
        },
      },
      phone: "555-555-5555",
      website: "lordoftherings.com",
      company: {
        name: "Council of the Wise",
        catchPhrase:
          "All we have to decide is what to do with the time that is given us",
        bs: "Magic",
      },
    },
    {
      id: 40,
      name: "Willy Wonka",
      username: "wwonka",
      email: "willy@wonka.com",
      address: {
        street: "Wonka Chocolate Factory",
        suite: "",
        city: "London",
        zipcode: "",
        geo: {
          lat: "51.5074",
          lng: "-0.1278",
        },
      },
      phone: "555-555-5555",
      website: "charlieandthechocolatefactory.com",
      company: {
        name: "Wonka Industries",
        catchPhrase: "Pure imagination",
        bs: "Candy manufacturing",
      },
    },
    {
      id: 41,
      name: "Indiana Jones",
      username: "indy",
      email: "indiana.jones@marshall.edu",
      address: {
        street: "Marshall College",
        suite: "",
        city: "Bedford",
        zipcode: "",
        geo: {
          lat: "39.1653",
          lng: "-86.5264",
        },
      },
      phone: "555-555-5555",
      website: "indianajones.com",
      company: {
        name: "Marshall College",
        catchPhrase:
          "Archaeology is the search for fact... not truth. If it's truth you're interested in, Dr. Tyree's philosophy class is right down the hall.",
        bs: "Archaeology",
      },
    },
    {
      id: 42,
      name: "Darth Vader",
      username: "dvader",
      email: "darth.vader@empire.com",
      address: {
        street: "Death Star",
        suite: "",
        city: "Deep space",
        zipcode: "",
        geo: {
          lat: "0",
          lng: "0",
        },
      },
      phone: "555-555-5555",
      website: "starwars.com",
      company: {
        name: "Galactic Empire",
        catchPhrase: "Peace through power.",
        bs: "Military",
      },
    },
    {
      id: 43,
      name: "Michael Scott",
      username: "mscott",
      email: "mscott@dundermifflin.com",
      address: {
        street: "1725 Slough Avenue",
        suite: "",
        city: "Scranton",
        zipcode: "18503",
        geo: {
          lat: "41.4067",
          lng: "-75.6674",
        },
      },
      phone: "555-555-5555",
      website: "theoffice.com",
      company: {
        name: "Dunder Mifflin Paper Company",
        catchPhrase: "Limitless paper in a paperless world.",
        bs: "Paper",
      },
    },
    {
      id: 44,
      name: "Harry Potter",
      username: "hpotter",
      email: "harry@hogwarts.edu",
      address: {
        street: "Hogwarts School of Witchcraft and Wizardry",
        suite: "",
        city: "Hogsmeade",
        zipcode: "",
        geo: {
          lat: "56.2281",
          lng: "-3.7908",
        },
      },
      phone: "555-555-5555",
      website: "wizardingworld.com",
      company: {
        name: "Hogwarts School of Witchcraft and Wizardry",
        catchPhrase: "Draco dormiens nunquam titillandus",
        bs: "Magic",
      },
    },
    {
      id: 45,
      name: "James Bond",
      username: "jbond",
      email: "james.bond@mi6.gov.uk",
      address: {
        street: "85 Albert Embankment",
        suite: "",
        city: "London",
        zipcode: "SE1 7TP",
        geo: {
          lat: "51.4927",
          lng: "-0.1225",
        },
      },
      phone: "555-555-5555",
      website: "007.com",
      company: {
        name: "MI6",
        catchPhrase: "We do not discuss our operations.",
        bs: "Espionage",
      },
    },
    {
      id: 46,
      name: "Rick Sanchez",
      username: "rsanchez",
      email: "rick.sanchez@dimensionc137.com",
      address: {
        street: "The Smith Residence",
        suite: "",
        city: "Morty Town",
        zipcode: "",
        geo: {
          lat: "36.1447",
          lng: "-86.8027",
        },
      },
      phone: "555-555-5555",
      website: "rickandmorty.com",
      company: {
        name: "Smith Family",
        catchPhrase: "Wubba lubba dub dub!",
        bs: "Science",
      },
    },
    {
      id: 47,
      name: "Pikachu",
      username: "pikachu",
      email: "pikachu@pokemon.com",
      address: {
        street: "Pallet Town",
        suite: "",
        city: "Kanto",
        zipcode: "",
        geo: {
          lat: "35.6895",
          lng: "139.6917",
        },
      },
      phone: "555-555-5555",
      website: "pokemon.com",
      company: {
        name: "Professor Oak's Laboratory",
        catchPhrase: "Gotta catch 'em all!",
        bs: "Pokemon training",
      },
    },
    {
      id: 48,
      name: "Marge Simpson",
      username: "msimpson",
      email: "marge.simpson@springfield.com",
      address: {
        street: "742 Evergreen Terrace",
        suite: "",
        city: "Springfield",
        zipcode: "",
        geo: {
          lat: "38.7814",
          lng: "-77.0182",
        },
      },
      phone: "555-555-5555",
      website: "thesimpsons.com",
      company: {
        name: "Simpson Family",
        catchPhrase: "Mmmmm... donuts!",
        bs: "Nuclear power",
      },
    },
    {
      id: 49,
      name: "Willy Wonka",
      username: "wwonka",
      email: "willy.wonka@wonkaindustries.com",
      address: {
        street: "Wonka Factory",
        suite: "",
        city: "Chocolate River",
        zipcode: "",
        geo: {
          lat: "51.5074",
          lng: "-0.1278",
        },
      },
      phone: "555-555-5555",
      website: "wonka.com",
      company: {
        name: "Wonka Industries",
        catchPhrase:
          "We are the music makers, and we are the dreamers of dreams.",
        bs: "Candy Manufacturing",
      },
    },
    {
      id: 50,
      name: "Homer Simpson",
      username: "hsimpson",
      email: "homer.simpson@springfield.com",
      address: {
        street: "742 Evergreen Terrace",
        suite: "",
        city: "Springfield",
        zipcode: "",
        geo: {
          lat: "38.7814",
          lng: "-77.0182",
        },
      },
      phone: "555-555-5555",
      website: "thesimpsons.com",
      company: {
        name: "Springfield Nuclear Power Plant",
        catchPhrase: "Mmmmm... beer!",
        bs: "Nuclear power",
      },
    },
  ]